// tienda-online-react/tienda-react/src/components/ProductoCard.jsx
/**
 * ProductoCard.jsx
 * Tarjeta individual de producto.
 * Gestiona: visualización, efecto hover con carrusel, y botón de añadir al carrito.
 */

import React from "react";
import { useImageCarousel } from "../hooks/useImageCarousel";

export default function ProductoCard({ producto, onAgregarAlCarrito }) {
  const { id, codigo, descripcion, precio, stock, imagenes } = producto;

  // Hook del carrusel: sabe qué imagen mostrar y nos da los event handlers
  const { imagenActual, manejadores } = useImageCarousel(imagenes.length);

  // Sin stock disponible (todo está en el carrito u original a 0)
  const sinStock = stock <= 0;

  return (
    <div className={`producto-card d-flex flex-column position-relative ${sinStock ? "sin-stock" : ""}`}>
      {/* Badge Flotante para el código/categoría */}
      <div className="position-absolute top-0 start-0 m-3 z-3">
        <span className="badge bg-light text-dark fw-semibold shadow-sm rounded-pill px-3 py-2 border">
          {codigo}
        </span>
      </div>

      {/* ── Imagen con efecto hover + carrusel ── */}
      <div className="imagen-wrapper" {...manejadores}>
        {imagenes && imagenes.length > 0 ? (
          <>
            <img
              src={imagenes[imagenActual]}
              alt={descripcion}
              className="producto-imagen"
            />
            {/* Indicadores de imagen (bolitas) */}
            {imagenes.length > 1 && (
              <div className="imagen-indicadores">
                {imagenes.map((_, i) => (
                  <span
                    key={i}
                    className={`indicador ${i === imagenActual ? "activo" : ""}`}
                  />
                ))}
              </div>
            )}
          </>
        ) : (
          <div className="h-100 w-100 d-flex flex-column justify-content-center align-items-center text-muted bg-light">
            <i className="bi bi-image" style={{ fontSize: '3rem', opacity: 0.5 }}></i>
            <span className="fw-semibold mt-2" style={{ opacity: 0.7 }}>No Image</span>
          </div>
        )}
      </div>

      {/* ── Información del producto ── */}
      <div className="card-body d-flex flex-column h-100">
        <h5 className="card-title fw-bold text-truncate mb-2">{descripcion}</h5>
        
        <div className="mt-auto d-flex justify-content-between align-items-end pt-3">
          <div>
            <div className="fs-4 fw-bolder text-primary lh-1 mb-1">
              {precio.toFixed(2)} €
            </div>
            <div className={`small fw-semibold ${sinStock ? "text-danger" : "text-muted"}`}>
              {sinStock ? "❌ Agotado" : `✓ Stock: ${stock}`}
            </div>
          </div>

          <button
            className="btn btn-primary rounded-circle p-2 d-flex justify-content-center align-items-center"
            style={{ width: "45px", height: "45px" }}
            disabled={sinStock}
            onClick={() => onAgregarAlCarrito(id)}
            title={sinStock ? "Producto agotado" : "Añadir al carrito"}
          >
            {sinStock ? (
              <i className="bi bi-x-lg fs-5" />
            ) : (
              <i className="bi bi-cart-plus-fill fs-5" />
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

// tienda-online-angular/tienda-angular/src/app/components/producto-card/producto-card.component.ts
import { Component, input, computed, inject, signal, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Producto } from '../../models/producto.model';
import { CarritoService } from '../../services/carrito.service';

@Component({
  selector: 'app-producto-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './producto-card.component.html',
  styleUrls: ['./producto-card.component.css']
})
export class ProductoCardComponent implements OnDestroy {
  private carritoService = inject(CarritoService);

  producto = input.required<Producto>();

  sinStock = computed(() => this.producto().stock <= 0);

  imagenActual = signal(0);
  private intervaloId: any = null;

  iniciarCarrusel() {
    const total = this.producto().imagenes?.length || 0;
    if (total <= 1 || this.intervaloId) return;

    this.intervaloId = setInterval(() => {
      this.imagenActual.update(prev => (prev + 1) % total);
    }, 1500);
  }

  detenerCarrusel() {
    if (this.intervaloId) {
      clearInterval(this.intervaloId);
      this.intervaloId = null;
    }
    this.imagenActual.set(0);
  }

  agregarAlCarrito() {
    this.carritoService.agregarAlCarrito(this.producto().id);
  }

  ngOnDestroy() {
    if (this.intervaloId) {
      clearInterval(this.intervaloId);
    }
  }
}

<div class="producto-card d-flex flex-column position-relative" [class.sin-stock]="sinStock()">
  <!-- Muestra el código del producto -->
  <div class="position-absolute top-0 start-0 m-3 z-3">
    <span class="badge bg-light text-dark fw-semibold shadow-sm rounded-pill px-3 py-2 border">
      {{ producto().codigo }}
    </span>
  </div>

  <!-- Contenedor de la imagen. Carrusel interactivo en hover. -->
  <div class="imagen-wrapper" (mouseenter)="iniciarCarrusel()" (mouseleave)="detenerCarrusel()">
    <ng-container *ngIf="producto().imagenes && producto().imagenes.length > 0; else noImage">
      <img [src]="producto().imagenes[imagenActual()]" [alt]="producto().descripcion" class="producto-imagen" />
      
      <!-- Indicadores de imagen (bolitas) -->
      @if (producto().imagenes.length > 1) {
        <div class="imagen-indicadores">
          @for (img of producto().imagenes; track $index) {
            <span class="indicador" [class.activo]="$index === imagenActual()"></span>
          }
        </div>
      }
    </ng-container>
    <ng-template #noImage>
      <div class="h-100 w-100 d-flex flex-column justify-content-center align-items-center text-muted bg-light">
        <i class="bi bi-image" style="font-size: 3rem; opacity: 0.5;"></i>
        <span class="fw-semibold mt-2" style="opacity: 0.7;">No Image</span>
      </div>
    </ng-template>
  </div>

  <!-- Información del producto -->
  <div class="card-body d-flex flex-column h-100">
    <h5 class="card-title fw-bold text-truncate mb-2">{{ producto().descripcion }}</h5>

    <div class="mt-auto d-flex justify-content-between align-items-end pt-3">
      <div>
        <div class="fs-4 fw-bolder text-primary lh-1 mb-1">
          {{ producto().precio | number:'1.2-2' }} €
        </div>
        <div class="small fw-semibold" [ngClass]="sinStock() ? 'text-danger' : 'text-muted'">
          {{ sinStock() ? "❌ Agotado" : ("✓ Stock: " + producto().stock) }}
        </div>
      </div>

      <button class="btn btn-primary rounded-circle p-2 d-flex justify-content-center align-items-center"
        style="width: 45px; height: 45px;" [disabled]="sinStock()" (click)="agregarAlCarrito()"
        [title]="sinStock() ? 'Producto agotado' : 'Añadir al carrito'">
        <ng-container *ngIf="sinStock(); else canBuy">
          <i class="bi bi-x-lg fs-5"></i>
        </ng-container>
        <ng-template #canBuy>
          <i class="bi bi-cart-plus-fill fs-5"></i>
        </ng-template>
      </button>
    </div>
  </div>
</div>
