// tienda-online-react/tienda-react/src/components/Carrito.jsx
/**
 * Carrito.jsx
 * Columna derecha: muestra los items añadidos, permite modificar cantidades
 * (incrementar / decrementar) y lanza el pedido.
 */

import React from "react";

export default function Carrito({
  items,
  onIncrementar,
  onDecrementar,
  onRealizarPedido,
}) {
  const total = items.reduce(
    (acc, { producto, cantidad }) => acc + producto.precio * cantidad,
    0
  );

  const carritoVacio = items.length === 0;

  return (
    <div className="carrito-panel">
      <h4 className="mb-4 d-flex align-items-center">
        <i className="bi bi-cart-check fs-3 me-2 text-primary" />
        <span className="fw-bold fs-4">Mi Cesta</span>
        {!carritoVacio && (
          <span className="badge bg-primary rounded-pill ms-auto">
            {items.reduce((acc, i) => acc + i.cantidad, 0)} items
          </span>
        )}
      </h4>

      {/* ── Estado vacío ── */}
      {carritoVacio ? (
        <div className="text-center text-muted py-5 d-flex flex-column align-items-center">
          <div className="bg-light rounded-circle d-flex justify-content-center align-items-center mb-3" style={{width: '80px', height: '80px'}}>
            <i className="bi bi-cart-x text-secondary" style={{ fontSize: "2.5rem" }} />
          </div>
          <p className="fs-5 fw-medium mb-1">Tu cesta está vacía</p>
          <p className="small">¡Añade algunos productos para empezar!</p>
        </div>
      ) : (
        <div className="d-flex flex-column">
          {/* ── Lista de items ── */}
          <div className="mb-4 d-flex flex-column gap-3">
            {items.map(({ producto, cantidad }) => (
              <div
                key={producto.id}
                className="carrito-item-row p-3 border bg-white"
              >
                <div className="d-flex align-items-start gap-3">
                  {/* Miniatura fija a la izquierda */}
                  {producto.imagenes && producto.imagenes.length > 0 ? (
                    <img
                      src={producto.imagenes[0]}
                      alt={producto.descripcion}
                      className="carrito-miniatura flex-shrink-0"
                    />
                  ) : (
                    <div className="carrito-miniatura flex-shrink-0 d-flex justify-content-center align-items-center bg-secondary bg-opacity-10 border text-muted">
                      <i className="bi bi-image" style={{ fontSize: '1.2rem', opacity: 0.5 }}></i>
                    </div>
                  )}

                  {/* Columna derecha con Textos arriba y Controles abajo (a prueba de desbordes) */}
                  <div className="d-flex flex-column flex-grow-1" style={{ minWidth: 0 }}>
                    
                    {/* Textos: Nombre truncado seguro gracias al minWidth: 0 */}
                    <p className="mb-0 fw-bold text-truncate" title={producto.descripcion}>
                      {producto.descripcion}
                    </p>
                    <p className="mb-2 text-muted small fw-medium">
                      {producto.precio.toFixed(2)} € × {cantidad}
                    </p>

                    {/* Fila del precio total e incrementadores envueltos horizontalmente */}
                    <div className="d-flex flex-wrap justify-content-between align-items-center mt-auto gap-2">
                       <span className="fw-bolder text-primary">
                         {(producto.precio * cantidad).toFixed(2)} €
                       </span>

                       {/* Bloque de botones protegidos contra encogimiento con flex-shrink-0 */}
                       <div className="d-flex align-items-center gap-2 bg-secondary bg-opacity-10 p-1 rounded-pill flex-shrink-0">
                         <button
                           className="btn btn-sm btn-xs border-0 rounded-circle d-flex align-items-center justify-content-center bg-body shadow-sm text-danger"
                           onClick={() => onDecrementar(producto.id)}
                           title="Quitar uno"
                           style={{ width: "26px", height: "26px" }}
                         >
                           <i className="bi bi-dash-lg fw-bold" />
                         </button>
                         <span className="fw-bold small d-inline-block text-center" style={{minWidth: '20px'}}>
                           {cantidad}
                         </span>
                         <button
                           className="btn btn-sm btn-xs border-0 rounded-circle d-flex align-items-center justify-content-center bg-body shadow-sm text-primary"
                           onClick={() => onIncrementar(producto.id)}
                           title="Añadir uno más"
                           disabled={producto.stock <= 0}
                           style={{ width: "26px", height: "26px" }}
                         >
                           <i className="bi bi-plus-lg fw-bold" />
                         </button>
                       </div>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* ── Total ── */}
          <div className="bg-light p-3 rounded-3 mb-4">
            <div className="d-flex justify-content-between align-items-center mb-2">
              <span className="text-muted fw-medium">Subtotal</span>
              <span className="fw-semibold">{total.toFixed(2)} €</span>
            </div>
            <div className="d-flex justify-content-between align-items-center mb-2">
              <span className="text-muted fw-medium">Envío</span>
              <span className="fw-semibold text-success">Gratis</span>
            </div>
            <hr className="my-2 opacity-10" />
            <div className="d-flex justify-content-between align-items-center mt-2">
               <span className="fw-bold fs-5">Total</span>
               <span className="fs-4 fw-bolder text-primary">{total.toFixed(2)} €</span>
            </div>
          </div>

          {/* ── Botón pedido ── */}
          <button
            className="btn btn-primary w-100 py-3 fw-bold fs-5 rounded-3 d-flex justify-content-center align-items-center gap-2 shadow-sm"
            onClick={onRealizarPedido}
          >
            <i className="bi bi-bag-check-fill" />
            Finalizar Compra
          </button>
        </div>
      )}
    </div>
  );
}

// tienda-online-angular/tienda-angular/src/app/components/carrito/carrito.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CarritoService } from '../../services/carrito.service';

@Component({
  selector: 'app-carrito',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './carrito.component.html',
  styleUrls: ['./carrito.component.css']
})
export class CarritoComponent {
  carritoService = inject(CarritoService);
}

<div class="carrito-panel">
  <div class="d-flex align-items-center justify-content-between mb-4 border-bottom border-light pb-3"
    style="border-bottom-color: rgba(0,0,0,0.05);">
    <h4 class="mb-0 fw-bold d-flex align-items-center gap-2">
      <i class="bi bi-cart3 text-primary"></i> Mi Cesta
    </h4>
    <span class="badge bg-primary rounded-pill px-3 py-2 fs-6 shadow-sm">
      {{ carritoService.cantidadItems() }} ítems
    </span>
  </div>

  @if (carritoService.carrito().length === 0) {
  <div class="text-center py-5 text-muted fade-enter">
    <div class="mb-3">
      <i class="bi bi-cart-x text-secondary" style="font-size: 3.5rem; opacity: 0.5;"></i>
    </div>
    <h5 class="fw-semibold">Tu cesta está vacía</h5>
    <p class="small mb-0">¡Explora nuestro catálogo y añade productos increíbles!</p>
  </div>
  } @else {
  <div class="carrito-items-container fade-enter">
    @for (item of carritoService.carrito(); track item.producto.id) {
    <div class="carrito-item-row p-3 border bg-white mb-3">
      <div class="d-flex align-items-start gap-3">
        <ng-container *ngIf="item.producto.imagenes && item.producto.imagenes.length > 0; else noImageCart">
          <img [src]="item.producto.imagenes[0]" alt="{{item.producto.descripcion}}"
            class="carrito-miniatura flex-shrink-0">
        </ng-container>
        <ng-template #noImageCart>
          <div
            class="carrito-miniatura flex-shrink-0 d-flex justify-content-center align-items-center bg-secondary bg-opacity-10 border text-muted">
            <i class="bi bi-image" style="font-size: 1.2rem; opacity: 0.5;"></i>
          </div>
        </ng-template>

        <div class="d-flex flex-column flex-grow-1" style="min-width: 0;">
          <p class="mb-0 fw-bold text-truncate" [title]="item.producto.descripcion">
            {{item.producto.descripcion}}
          </p>
          <p class="mb-2 text-muted small fw-medium">
            {{ item.producto.precio | number:'1.2-2' }} € × {{ item.cantidad }}
          </p>

          <div class="d-flex flex-wrap justify-content-between align-items-center mt-auto gap-2">
            <span class="fw-bolder text-primary">
              {{ (item.producto.precio * item.cantidad) | number:'1.2-2' }} €
            </span>

            <div class="d-flex align-items-center gap-2 bg-secondary bg-opacity-10 p-1 rounded-pill flex-shrink-0">
              <button
                class="btn btn-sm btn-xs border-0 rounded-circle d-flex align-items-center justify-content-center bg-body shadow-sm text-danger"
                (click)="carritoService.decrementarEnCarrito(item.producto.id)" title="Quitar uno"
                style="width: 26px; height: 26px;">
                <i class="bi bi-dash-lg fw-bold"></i>
              </button>
              <span class="fw-bold small d-inline-block text-center" style="min-width: 20px;">
                {{ item.cantidad }}
              </span>
              <button
                class="btn btn-sm btn-xs border-0 rounded-circle d-flex align-items-center justify-content-center bg-body shadow-sm text-primary"
                (click)="carritoService.agregarAlCarrito(item.producto.id)" [disabled]="item.producto.stock <= 0"
                title="Añadir uno más" style="width: 26px; height: 26px;">
                <i class="bi bi-plus-lg fw-bold"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
    }
  </div>
  }

  <div class="mt-4 pt-3 border-top border-light" style="border-top-color: rgba(0,0,0,0.05);">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <span class="text-muted fw-semibold">Total a pagar:</span>
      <span class="fs-3 fw-bolder text-primary">{{ carritoService.total() | number:'1.2-2' }} €</span>
    </div>

    <button class="btn btn-primary w-100 py-3 fw-bold shadow-sm d-flex justify-content-center align-items-center gap-2"
      style="border-radius: 12px; font-size: 1.1rem;" [disabled]="carritoService.carrito().length === 0"
      (click)="carritoService.realizarPedido()">
      <span>Realizar Pedido</span>
      <i class="bi bi-arrow-right-circle-fill"></i>
    </button>
  </div>
</div>
